{% set name = "mayavi" %}
{% set version = "4.8.1" %}
{% set sha256 = "903dc4fe340ddfbb5245b3da92d244912b36f2043aaeea938788689fb965cb1c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: mayavi-{{ version }}.tar.gz
  url: https://github.com/enthought/mayavi/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-Fixed-vtk.patch

build:
  number: 0
  entry_points:
    - mayavi2 = mayavi.scripts.mayavi2:main
    - tvtk_doc = tvtk.tools.tvtk_doc:main
  skip: True  # [win and py<37]
  ignore_run_exports:
    - pyqt    # [linux and aarch64]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make    # [linux and aarch64]
    - patch
  host:
    - pip
    - python
    - apptools
    - numpy
    - setuptools
    - sphinx  # [osx or (linux and aarch64)]
    - traitsui
    - vtk
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - vtk
    - traitsui
    - pyface
    - apptools
    - envisage
    - pyqt >=4,<6
    - setuptools

test:
  commands:
    - mayavi2 --help
  imports:
    - tvtk
    - tvtk.array_ext
    - mayavi

about:
  home: http://docs.enthought.com/mayavi/mayavi/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Mayavi scientific data 3-dimensional visualizers
  description: |
    Mayavi2 seeks to provide easy and interactive visualization of 3D data, or 3D plotting.
    It does this by using an optional, rich user interface, ready to use 3D visualization functionality
    similar to matlab, and harnessing the power of VTK without forcing you to learn it.
  doc_url: http://docs.enthought.com/mayavi/mayavi
  dev_url: https://github.com/enthought/mayavi

extra:
  recipe-maintainers:
    - msarahan
    - grlee77
    - hadim
    - dfroger
    - cadair
