travis:
  secure:
    BINSTAR_TOKEN: KVd//RkEhMRfoz9qEikwV7b1XR/Zvbql0OdFKJXZstxqa0+FlGEURjA6+3MIRwhozs0FdS8C4yx7LZyIdMqEAoqcTkrgY0Qv1PPwDIqSwuJLp97Xt9E93q86LrhehLrECd4xgiMbM/CmduXQ65A6LvW5IZgRqIFips1+ZounYUWNeVTnoDtegZNe1FGel5ygNOfbPkk82qN2swRalxsyi0/byi8dpOjyih26tQ0NEIEkOqYu+98djKuDBXUaKN029J5rSMpw0XhT9m3RpdoNKvX8rR5odRqQrueEhgBbHdAC15UTDFxzge8dU/o3nI6Ldye+nlR8U5dfD5dLymmQdssguRBCOR+EcTUIB9HtgNLuJaVIESY3ljcWjAfbKIbFC9srR6h94acJL2/RpZVt5Oc1kk4iEunvUz/l39TrQrtnnssT6ESulXA5E0LxSmrzEKQpZFgAOB32qPza8iooAC5QI+T4RPf//+ZWNFQQ2lI51XTQ2A6JLE6OKuq8H6wKf6OIVcNGr4UM7O5HMqXE1IDI6M6L3obaH38hcIo2mSFyqeiiNQXddIpp1cahnz0/+ruy2lsR/kmimvuq3vtpLcYPwSurLlFs+lXmm4DuckD70cH4+8sdfU8qxvV8Q7JrHr9wIcDeZEKm7yhnxSy3KZumvNONnbdQWV0G4lgimIc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
