travis:
  secure:
    BINSTAR_TOKEN: 0m7nsIplNXgoiJjfttFlmrehpRrTuiQEj4w71rJe+eYwGCz3XXp3bISWIA+yIX3ygFx5SQWp3h5synoEw/dhSZcgKu2tTweY5CYmaJJUzS+FH47arzxMOxI0UsLzBU50sOgxDagMrr4LolWgtZ/3VDmHCycP9YgHcKcTonWpV2txnLWQoh7k+hWLlsGavwzm8n6o4nI8O/z9vpBF7Uyou25XqNyf8gFbdwcyP1EdF4nW5QTAOkKoD+UR8AyXPD3ErMYD8H3KXx+tqhRaeEaRI2WhvG0CN5FDWzvFNDU/3GQLOA03/BLGeyKfK67eT6nL2LpgRJ2SxuGS+7Zl/AEu6PlJkr7Ey7cQqOGZ1eyB3SZDftbS0xAVW8yENRX52NHeg4GZDAu4SDlM65yDKyyBQEhfCESKDOCP8Q1FjvdQU3/de5xztizwCO5qYnfGuVir2QQ6sOV0lAuJu+AV5dYF7iOV5Ojx7OFPwBwjxWGcr2o4Th/vsTUXU5tu6SNvJkNCVn8ZbetJHy0mFvYe7EsUgkYIZ+TzjQzthIgHzDc2BDxb76scJhBP0KgnNyelY31DN5wcei66KO0/siekkYPYIsPsnz/CDaMxYbqyjA3e2v2gBFgPEzJNYwe3YiuAFK47C+y1IYlsOuy0YWHNzHaZypP0ZPXwNnXuev/hrvBoOjg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
